// file: latex.c
// vim:fileencoding=utf-8:ft=c:tabstop=2
//
// Author: R.F. Smith <rsmith@xs4all.nl>
// Copyright © 2025 R.F. Smith <rsmith@xs4all.nl>
// Created: 2025-08-11 20:20:22 +0200
// Last modified: 2025-08-16T23:28:11+0200

#include "core.h"
#include "version.h"

#include <string.h>
#include <stdio.h>
#include <math.h>

static void engprop(Laminate *pl);
static void matrices(Laminate *pl);
extern void text_fea(Laminate *pl);

void html_out(Laminate *pl, bool eng, bool mat, bool fea)
{
  puts("<!DOCTYPE html>");
  puts("<html lang=\"en-US\">");
  puts("<head><meta charset=\"UTF-8\">"
       "<meta name=\"description\" content=\"lamprop output\">");
  puts("<title>lamprop output</title>");
  puts("</head>");
  puts("<body>");
  puts("<!-- outer table -->");
  puts("<table cellpadding=\"10%\">");
  printf("<caption><strong>Properties of %s</strong></caption>\n", sv8cstring(pl->name));
  puts("<tbody align=\"center\">");
  puts("<tr><td  align=\"center\" colspan=\"2\">Generated by lamprop version "
       VERSION".</td></tr>");
  puts("<!-- first row; tables -->");
  puts("<tr><td>");
  puts("<table border=\"1\" frame=\"hsides\"");
  puts("rules=\"groups\" cellpadding=\"5%\">");
  puts("<caption><strong>Laminate stacking</strong></caption>");
  puts("<thead align=\"right\">");
  puts("<tr><td>Layer</td><td>weight</td>");
  puts("<td>angle</td><td>vf</td><td align=\"left\">fiber type</td></tr>");
  puts("<tr><td></td><td>[g/m&sup2;]</td><td>[&deg;]</td><td>[%]</td></tr>");
  puts("</thead>");
  puts("<tbody align=\"right\">");
  for (int32_t k = 0; k < pl->nlayers; k++) {
    Lamina *la = pl->layers + k;
    puts("<tr>");
    printf("<td>%3d</td><td>%6g</td><td>%5g</td>", k+1, la->fiber_weight,
           180*la->angle/M_PI);
    printf("<td>%4.3g</td><td align=\"left\">%s</td>\n",
           100*la->vf, sv8cstring(la->f.name));
    puts("</tr>");
  }
  puts("</tbody>");
  puts("</table>");
  puts("</td>");
  puts("<td>");
  puts("<table border=\"1\" frame=\"hsides\" rules=\"groups\" cellpadding=\"5%\">");
  puts("<caption><strong>Physical properties</strong></caption>");
  puts("<thead align=\"right\">");
  puts("<tr><td>Property</td><td>Value</td><td align=\"left\">Dimension</td></tr>");
  puts("</thead>");
  puts("<tbody align=\"right\">");
  printf("<tr><td>v<sub>f</sub></td><td>%4.1f</td><td align=\"left\">%%</td></tr>\n",
         100*pl->vf);
  printf("<tr><td>w<sub>f</sub></td><td>%4.1f</td><td align=\"left\">%%</td></tr>\n",
         100*pl->wf);
  printf("<tr><td>thickness</td><td>%.2f</td><td align=\"left\">mm</td></tr>\n",
         pl->thickness);
  printf("<tr><td>density</td><td>%4.2f</td><td align=\"left\">g/cm&sup3;</td></tr>\n",
         pl->ρ);
  printf("<tr><td>weight</td><td>%.0f</td><td align=\"left\">g/m&sup2;</td></tr>\n",
         pl->fiber_weight + pl->resin_weight);
  printf("<tr><td>resin</td><td>%.0f</td><td align=\"left\">g/m&sup2;</td></tr>\n",
         pl->resin_weight);
  if (eng) {
    engprop(pl);
  }
  puts("</tbody>");
  puts("</table>");
  puts("</td>");
  puts("</tr>");
  if (mat) {
    matrices(pl);
  }
  if (fea) {
    puts("<tr>");
    puts("<!-- next row, stiffness tensor -->");
    puts("<td colspan=\"2\" align=\"left\">");
    puts("<pre>");
    text_fea(pl);
    puts("</pre>");
    puts("</td>");
    puts("</tr>");
  }
  puts("");
  fflush(stdout);
}

void engprop(Laminate *pl)
{
  puts("</tbody>");
  puts("<tbody>");
  puts("<tr><td colspan=\"6\" align=\"center\">"
       "<strong>Engineering properties</strong></td></tr>");
  puts("<tr><td colspan=\"3\" align=\"center\"><strong>In-plane</strong></td>");
  puts("<td colspan=\"3\" align=\"center\">"
       "<strong>3D stiffness tensor</strong></td></tr>");
  puts("<tr>");
  printf("<td>E<sub>x</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->Ex);
  printf("<td>E<sub>x</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->tEx);
  puts("</tr>");
  puts("<tr>");
  printf("<td>E<sub>y</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->Ey);
  printf("<td>E<sub>y</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->tEy);
  puts("</tr>");
  puts("<tr>");
  printf("<td>E<sub>z</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->Ez);
  printf("<td>E<sub>z</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->tEz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>G<sub>xy</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->Gxy);
  printf("<td>G<sub>xy</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->tGxy);
  puts("</tr>");
  puts("<tr>");
  printf("<td>G<sub>xz</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->Gxz);
  printf("<td>G<sub>xz</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->tGxz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>G<sub>yz</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->Gyz);
  printf("<td>G<sub>yz</sub></td><td>%8.0f</td><td align=\"left\">MPa</td>\n", pl->tGyz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>&nu;<sub>xy</sub></td><td>%.4f</td><td align=\"left\">-</td>\n", pl->νxy);
  printf("<td>&nu;<sub>xy</sub></td><td>%.4f</td><td align=\"left\">-</td>\n", pl->tνxy);
  puts("</tr>");
  puts("<tr>");
  printf("<td>&nu;<sub>yx</sub></td><td>%.4f</td><td align=\"left\">-</td>\n", pl->νyx);
  printf("<td>&nu;<sub>xz</sub></td><td>%.4f</td><td align=\"left\">-</td>\n", pl->tνxz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>&alpha;<sub>x</sub></td><td>%.4g</td>"
         "<td align=\"left\">K<sup>-1</sup></td>\n", pl->αx);
  printf("<td>&nu;<sub>yz</sub></td><td>%.4f</td><td align=\"left\">-</td>\n", pl->tνyz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>&alpha;<sub>y</sub></td><td>%.4g</td>"
         "<td align=\"left\">K<sup>-1</sup></td>\n", pl->αy);
  puts("</tr>");
}

void matrices(Laminate *pl)
{
  for (int32_t r = 0; r < 6; r++) {
    printf("%10e & %10e & %10e & %10e & %10e & %10e\\\\\n",
           pl->ABD[r][0], pl->ABD[r][1], pl->ABD[r][2],
           pl->ABD[r][3], pl->ABD[r][4], pl->ABD[r][5]);
  }
  printf("%10e & %10e\\\\\n", pl->H[0][0], pl->H[0][1]);
  printf("%10e & %10e\\\\\n", pl->H[1][0], pl->H[1][1]);
  for (int32_t r = 0; r < 6; r++) {
    printf("%10e & %10e & %10e & %10e & %10e & %10e\\\\\n",
           pl->C[r][0], pl->C[r][1], pl->C[r][2],
           pl->C[r][3], pl->C[r][4], pl->C[r][5]);
  }
}
