// file: latex.c
// vim:fileencoding=utf-8:ft=c:tabstop=2
// HTML output for lamprop.
//
// Author: R.F. Smith <rsmith@xs4all.nl>
// Copyright © 2025 R.F. Smith <rsmith@xs4all.nl>
// Created: 2025-08-11 20:20:22 +0200
// Last modified: 2026-02-17T01:52:48+0100

#include "core.h"
#include "version.h"
#include "sbuf.h"

#include <assert.h>
#include <stddef.h>
#include <stdio.h>
#include <math.h>

static void engprop(Laminate *pl);
static void matrices(Laminate *pl);
extern void text_fea(Laminate *pl);

void html_out(Laminate *pl, bool eng, bool mat, bool fea)
{
  assert(pl!=0);
  puts("<!DOCTYPE html>");
  puts("<html lang=\"en-US\">");
  puts("<head><meta charset=\"UTF-8\">"
       "<meta name=\"description\" content=\"lamprop output\">");
  puts("<title>lamprop output</title>");
  puts("</head>");
  puts("<body>");
  puts("<!-- outer table -->");
  puts("<table cellpadding=\"10%\">");
  printf("<caption><strong>Properties of %s</strong></caption>\n", sv8cstring(pl->name));
  puts("<tbody align=\"center\">");
  puts("<tr><td  align=\"center\" colspan=\"2\">Generated by lamprop-c version "
       VERSION".</td></tr>");
  puts("<!-- first row; tables -->");
  puts("<tr><td>");
  puts("<table border=\"1\" frame=\"hsides\"");
  puts("rules=\"groups\" cellpadding=\"5%\">");
  puts("<caption><strong>Laminate stacking</strong></caption>");
  puts("<thead align=\"right\">");
  puts("<tr><td>Layer</td><td>weight</td>");
  puts("<td>angle</td><td>vf</td><td align=\"left\">fiber type</td></tr>");
  puts("<tr><td></td><td>[g/m&sup2;]</td><td>[&deg;]</td><td>[%]</td></tr>");
  puts("</thead>");
  puts("<tbody align=\"right\">");
  for (int32_t k = 0; k < pl->nlayers; k++) {
    Lamina *la = pl->layers + k;
    if (la->comment.data && la->comment.len) {
      puts("<tr>");
      printf("<td  align=\"left\" colspan=\"5\">%s</td>\n", sv8cstring(la->comment));
      puts("</tr>");
    }
    puts("<tr>");
    printf("<td>%3d</td><td>%6g</td><td>%5g</td>", k+1, la->fiber_weight,
           180*la->angle/M_PI);
    printf("<td>%4.3g</td><td align=\"left\">%s</td>\n",
           100*la->vf, sv8cstring(la->f.name));
    puts("</tr>");
  }
  puts("</tbody>");
  puts("</table>");
  puts("</td>");
  puts("<td>");
  puts("<table border=\"1\" frame=\"hsides\" rules=\"groups\" cellpadding=\"5%\">");
  puts("<caption><strong>Physical properties</strong></caption>");
  puts("<thead align=\"right\">");
  puts("<tr><td>Property</td><td>Value</td><td align=\"left\">Dimension</td></tr>");
  puts("</thead>");
  puts("<tbody align=\"right\">");
  printf("<tr><td>v<sub>f</sub></td><td>%4.1f</td><td align=\"left\">%%</td></tr>\n",
         100*pl->vf);
  printf("<tr><td>w<sub>f</sub></td><td>%4.1f</td><td align=\"left\">%%</td></tr>\n",
         100*pl->wf);
  printf("<tr><td>thickness</td><td>%.2f</td><td align=\"left\">mm</td></tr>\n",
         pl->thickness);
  printf("<tr><td>density</td><td>%4.2f</td><td align=\"left\">g/cm&sup3;</td></tr>\n",
         pl->ρ);
  printf("<tr><td>weight</td><td>%.0f</td><td align=\"left\">g/m&sup2;</td></tr>\n",
         pl->fiber_weight + pl->resin_weight);
  printf("<tr><td>resin</td><td>%.0f</td><td align=\"left\">g/m&sup2;</td></tr>\n",
         pl->resin_weight);
  if (eng) {
    engprop(pl);
  }
  puts("</tbody>");
  puts("</table>");
  puts("</td>");
  puts("</tr>");
  if (mat) {
    matrices(pl);
  }
  if (fea) {
    puts("<tr>");
    puts("<!-- next row, stiffness tensor -->");
    puts("<td colspan=\"2\" align=\"left\">");
    puts("<pre>");
    text_fea(pl);
    puts("</pre>");
    puts("</td>");
    puts("</tr>");
  }
  puts("");
  fflush(stdout);
}

void engprop(Laminate *pl)
{
  puts("</tbody>");
  puts("<tbody>");
  puts("<tr><td colspan=\"6\" align=\"center\">"
       "<strong>Engineering properties</strong></td></tr>");
  puts("<tr><td colspan=\"3\" align=\"center\"><strong>In-plane</strong></td>");
  puts("<td colspan=\"3\" align=\"center\">"
       "<strong>3D stiffness tensor</strong></td></tr>");
  puts("<tr>");
  printf("<td>E<sub>x</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Ex);
  printf("<td>E<sub>x</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tEx);
  puts("</tr>");
  puts("<tr>");
  printf("<td>E<sub>y</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Ey);
  printf("<td>E<sub>y</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tEy);
  puts("</tr>");
  puts("<tr>");
  printf("<td>E<sub>z</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Ez);
  printf("<td>E<sub>z</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tEz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>G<sub>xy</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Gxy);
  printf("<td>G<sub>xy</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tGxy);
  puts("</tr>");
  puts("<tr>");
  printf("<td>G<sub>xz</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Gxz);
  printf("<td>G<sub>xz</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tGxz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>G<sub>yz</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Gyz);
  printf("<td>G<sub>yz</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tGyz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>&nu;<sub>xy</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->νxy);
  printf("<td>&nu;<sub>xy</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->tνxy);
  puts("</tr>");
  puts("<tr>");
  printf("<td>&nu;<sub>yx</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->νyx);
  printf("<td>&nu;<sub>xz</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->tνxz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>&alpha;<sub>x</sub></td><td>%9.4g</td>"
         "<td align=\"left\">K<sup>-1</sup></td>\n", pl->αx);
  printf("<td>&nu;<sub>yz</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->tνyz);
  puts("</tr>");
  puts("<tr>");
  printf("<td>&alpha;<sub>y</sub></td><td>%9.4g</td>"
         "<td align=\"left\">K<sup>-1</sup></td>\n", pl->αy);
  puts("</tr>");
}

// Print a formatted row from a matrix.
static void pr(int n, double mat[n][n], int row)
{
  Sbuf b = {0};
  sbuf_appends(&b, "          <td>");
  for (int32_t j = 0; j < n; j++) {
    double num = mat[row][j];
    if (fpclassify(num) == FP_ZERO || (-1e-7 <= num && num <= 1e-7 )) {
      sbuf_appends(&b, "0");
    } else if (isnan(num)) {
      sbuf_appends(&b, "NaN");
    } else if (isinf(num)) {
      char inf[4] = {0xE2, 0x88, 0x9E, 0};
      sbuf_appends(&b, inf);
    } else {
      sbuf_printf(&b, "%-10.4g", num);
    }
    if (j<(n-1)) {
      sbuf_appends(&b, "</td><td>");
    }
  }
  sbuf_appends(&b, "</td>");
  puts(b.data);
}

void matrices(Laminate *pl)
{
  char *fstr[6] = {
    "<td>N<sub>x</sub></td>",
    "<td>N<sub>y</sub></td>",
    "<td>N<sub>xy</sub></td>",
    "<td>M<sub>x</sub></td>",
    "<td>M<sub>y</sub></td>",
    "<td>M<sub>xy</sub></td>"
  };
  char *dstr[6] = {
    "<td>&epsilon;<sub>x</sub></td>",
    "<td>&epsilon;<sub>y</sub></td>",
    "<td>&gamma;<sub>xy</sub></td>",
    "<td>&kappa;<sub>x</sub></td>",
    "<td>&kappa;<sub>y</sub></td>",
    "<td>&kappa;<sub>xy</sub></td>",
  };
  puts("<tr>");
  puts("<!-- second row, stiffness or ABD matrix -->");
  puts("<td colspan=\"2\">");
  puts("<table border=\"1\" frame=\"vsides\" rules=\"groups\" cellpadding=\"5%\">");
  puts("<caption><strong>In-plane stiffness (ABD) matrix</strong></caption>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<colgroup span=\"6\"></colgroup>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<tbody align=\"center\">");
  puts("<tr>");
  puts(fstr[0]);
  puts("<td rowspan=\"6\">=</td>");
  pr(6, pl->ABD, 0);
  puts("<td rowspan=\"6\">&times;</td>");
  puts(dstr[0]);
  puts("</tr>");
  for (int32_t r = 1; r < 6; r++) {
    puts("<tr>");
    puts(fstr[r]);
    pr(6, pl->ABD, r);
    puts(dstr[r]);
    puts("</tr>");
  }
  puts("</tbody>");
  puts("</table>");
  puts("</td>");
  puts("</tr>");
  puts("<tr>");
  puts("<!-- third row, transverse stiffness or H matrix -->");
  puts("<td colspan=\"2\">");
  puts("<table border=\"1\" frame=\"vsides\" rules=\"groups\" cellpadding=\"5%\">");
  puts("<caption><strong>Transverse stiffness (H) matrix</strong></caption>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<colgroup span=\"2\"></colgroup>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<tbody align=\"center\">");
  puts("<tr>");
  puts("<td>V<sub>y</sub></td>");
  puts("<td rowspan=\"2\">=</td>");
  pr(2, pl->H, 0);
  puts("<td rowspan=\"2\">&times;</td>");
  puts("<td>&gamma;<sub>yz</sub></td>");
  puts("</tr>");
  puts("<tr>");
  puts("<td>V<sub>x</sub></td>");
  pr(2, pl->H, 1);
  puts("<td>&gamma;<sub>xz</sub></td>");
  puts("</tr>");
  puts("</tbody>");
  puts("</table>");
  puts("</td>");
  puts("</tr>");
  char *fstr2[6] = {
    "<td>&sigma;<sub>11</sub></td>",
    "<td>&sigma;<sub>22</sub></td>",
    "<td>&sigma;<sub>33</sub></td>",
    "<td>&sigma;<sub>23</sub></td>",
    "<td>&sigma;<sub>13</sub></td>",
    "<td>&sigma;<sub>12</sub></td>",
  };
  char *dstr2[6] = {
    "<td>&epsilon;<sub>11</sub></td>",
    "<td>&epsilon;<sub>22</sub></td>",
    "<td>&epsilon;<sub>33</sub></td>",
    "<td>2&epsilon;<sub>23</sub></td>",
    "<td>2&epsilon;<sub>13</sub></td>",
    "<td>2&epsilon;<sub>12</sub></td>",
  };
  puts("<tr>");
  puts("<!-- next row, stiffness tensor -->");
  puts("<td colspan=\"2\">");
  puts("<table border=\"1\" frame=\"vsides\" rules=\"groups\" cellpadding=\"5%\">");
  puts("<caption><strong>3D stiffness (C) tensor, contracted notation</strong></caption>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<colgroup span=\"6\"></colgroup>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<colgroup span=\"1\"></colgroup>");
  puts("<tbody align=\"center\">");
  puts("<tr>");
  puts(fstr2[0]);
  puts("<td rowspan=\"6\">=</td>");
  pr(6,pl-> C, 0),
  puts("<td rowspan=\"6\">&times;</td>");
  puts(dstr2[0]);
  puts("</tr>");
  for (int32_t r = 1; r < 6; r++) {
    puts("<tr>");
    puts(fstr2[r]);
    pr(6, pl->C, r);
    puts(dstr2[r]);
    puts("</tr>");
  }
  puts("</tbody>");
  puts("</table>");
  puts("</td>");
  puts("</tr>");
}
