// file: latex.c
// vim:fileencoding=utf-8:ft=c:tabstop=2
// HTML output for lamprop.
//
// Author: R.F. Smith <rsmith@xs4all.nl>
// Copyright © 2025 R.F. Smith <rsmith@xs4all.nl>
// Created: 2025-08-11 20:20:22 +0200
// Last modified: 2026-05-25T02:25:43+0200

#include "core.h"
#include "version.h"
#include "sbuf.h"
#include "setup.h"

#include <assert.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <math.h>

static void engprop(Laminate *pl, FILE *outfile);
static void matrices(Laminate *pl, FILE *outfile);
extern void text_fea(Laminate *pl, FILE *outfile);

void html_out(Laminate *pl, Options opt)
{
  assert(pl != 0);
  fputs("<!DOCTYPE html>\n", opt.outfile);
  fputs("<html lang=\"en-US\">\n", opt.outfile);
  fputs("<head><meta charset=\"UTF-8\">"
       "<meta name=\"description\" content=\"lamprop output\">", opt.outfile);
  fputs("<title>lamprop output</title>\n", opt.outfile);
  fputs("</head>\n", opt.outfile);
  fputs("<body>\n", opt.outfile);
  fputs("<!-- outer table -->\n", opt.outfile);
  fputs("<table cellpadding=\"10%\">\n", opt.outfile);
  fprintf(opt.outfile, "<caption><strong>Properties of %s</strong></caption>\n", sv8cstring(pl->name));
  fputs("<tbody align=\"center\">\n", opt.outfile);
  fputs("<tr><td  align=\"center\" colspan=\"2\">Generated by "
       LONG_VERSION".</td></tr>\n", opt.outfile);
  fputs("<!-- first row; tables -->\n", opt.outfile);
  fputs("<tr><td>\n", opt.outfile);
  fputs("<table border=\"1\" frame=\"hsides\"\n", opt.outfile);
  fputs("rules=\"groups\" cellpadding=\"5%\">\n", opt.outfile);
  fputs("<caption><strong>Laminate stacking</strong></caption>\n", opt.outfile);
  fputs("<thead align=\"right\">\n", opt.outfile);
  fputs("<tr><td>Layer</td><td>weight</td>\n", opt.outfile);
  fputs("<td>angle</td><td>vf</td><td align=\"left\">fiber type</td></tr>\n", opt.outfile);
  fputs("<tr><td></td><td>[g/m&sup2;]</td><td>[&deg;]</td><td>[%]</td></tr>\n", opt.outfile);
  fputs("</thead>\n", opt.outfile);
  fputs("<tbody align=\"right\">\n", opt.outfile);
  for (int32_t k = 0; k < pl->nlayers; k++) {
    Lamina *la = pl->layers + k;
    if (la->comment.data && la->comment.len) {
      fputs("<tr>\n", opt.outfile);
      fprintf(opt.outfile, "<td  align=\"left\" colspan=\"5\">%s</td>\n", sv8cstring(la->comment));
      fputs("</tr>\n", opt.outfile);
    } else if (la->symm) {
      fputs("<tr>\n", opt.outfile);
      fputs("<td  align=\"left\" colspan=\"5\">&horbar; symmetry line &horbar;</td>\n", opt.outfile);
      fputs("</tr>\n", opt.outfile);
    }
    fputs("<tr>\n", opt.outfile);
    fprintf(opt.outfile, "<td>%3d</td><td>%6g</td><td>%5g</td>", k + 1, la->fiber_weight,
           180 * la->angle / M_PI);
    fprintf(opt.outfile, "<td>%4.3g</td><td align=\"left\">%s</td>\n",
           100 * la->vf, sv8cstring(la->f.name));
    fputs("</tr>\n", opt.outfile);
  }
  fputs("</tbody>\n", opt.outfile);
  fputs("</table>\n", opt.outfile);
  fputs("</td>\n", opt.outfile);
  fputs("<td>\n", opt.outfile);
  fputs("<table border=\"1\" frame=\"hsides\" rules=\"groups\" cellpadding=\"5%\">\n", opt.outfile);
  fputs("<caption><strong>Physical properties</strong></caption>\n", opt.outfile);
  fputs("<thead align=\"right\">\n", opt.outfile);
  fputs("<tr><td>Property</td><td>Value</td><td align=\"left\">Dimension</td></tr>\n", opt.outfile);
  fputs("</thead>\n", opt.outfile);
  fputs("<tbody align=\"right\">\n", opt.outfile);
  fprintf(opt.outfile, "<tr><td>v<sub>f</sub></td><td>%4.1f</td><td align=\"left\">%%</td></tr>\n",
         100 * pl->vf);
  fprintf(opt.outfile, "<tr><td>w<sub>f</sub></td><td>%4.1f</td><td align=\"left\">%%</td></tr>\n",
         100 * pl->wf);
  fprintf(opt.outfile, "<tr><td>thickness</td><td>%.2f</td><td align=\"left\">mm</td></tr>\n",
         pl->thickness);
  fprintf(opt.outfile, "<tr><td>density</td><td>%4.2f</td><td align=\"left\">g/cm&sup3;</td></tr>\n",
         pl->ρ);
  fprintf(opt.outfile, "<tr><td>weight</td><td>%.0f</td><td align=\"left\">g/m&sup2;</td></tr>\n",
         pl->fiber_weight + pl->resin_weight);
  fprintf(opt.outfile, "<tr><td>resin</td><td>%.0f</td><td align=\"left\">g/m&sup2;</td></tr>\n",
         pl->resin_weight);
  if (opt.eng) {
    engprop(pl, opt.outfile);
  }
  fputs("</tbody>\n", opt.outfile);
  fputs("</table>\n", opt.outfile);
  fputs("</td>\n", opt.outfile);
  fputs("</tr>\n", opt.outfile);
  if (opt.matrix) {
    matrices(pl, opt.outfile);
  }
  if (opt.fea) {
    fputs("<tr>\n", opt.outfile);
    fputs("<!-- next row, stiffness tensor -->\n", opt.outfile);
    fputs("<td colspan=\"2\" align=\"left\">\n", opt.outfile);
    fputs("<pre>\n", opt.outfile);
    text_fea(pl, opt.outfile);
    fputs("</pre>\n", opt.outfile);
    fputs("</td>\n", opt.outfile);
    fputs("</tr>\n", opt.outfile);
  }
  fputs("\n", opt.outfile);
  fflush(opt.outfile);
}

void engprop(Laminate *pl, FILE *outfile)
{
  fputs("</tbody>\n", outfile);
  fputs("<tbody>\n", outfile);
  fputs("<tr><td colspan=\"6\" align=\"center\">"
       "<strong>Engineering properties</strong></td></tr>\n", outfile);
  fputs("<tr><td colspan=\"3\" align=\"center\"><strong>In-plane</strong></td>\n", outfile);
  fputs("<td colspan=\"3\" align=\"center\">"
       "<strong>3D stiffness tensor</strong></td></tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>E<sub>x</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Ex);
  fprintf(outfile, "<td>E<sub>x</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tEx);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>E<sub>y</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Ey);
  fprintf(outfile, "<td>E<sub>y</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tEy);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>E<sub>z</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Ez);
  fprintf(outfile, "<td>E<sub>z</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tEz);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>G<sub>xy</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Gxy);
  fprintf(outfile, "<td>G<sub>xy</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tGxy);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>G<sub>xz</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Gxz);
  fprintf(outfile, "<td>G<sub>xz</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tGxz);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>G<sub>yz</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->Gyz);
  fprintf(outfile, "<td>G<sub>yz</sub></td><td>%.0f</td><td align=\"left\">MPa</td>\n", pl->tGyz);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>&nu;<sub>xy</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->νxy);
  fprintf(outfile, "<td>&nu;<sub>xy</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->tνxy);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>&nu;<sub>yx</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->νyx);
  fprintf(outfile, "<td>&nu;<sub>xz</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->tνxz);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>&alpha;<sub>x</sub></td><td>%9.4g</td>"
         "<td align=\"left\">K<sup>-1</sup></td>\n", pl->αx);
  fprintf(outfile, "<td>&nu;<sub>yz</sub></td><td>%7.5f</td><td align=\"left\">-</td>\n", pl->tνyz);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fprintf(outfile, "<td>&alpha;<sub>y</sub></td><td>%9.4g</td>"
         "<td align=\"left\">K<sup>-1</sup></td>\n", pl->αy);
  fputs("</tr>\n", outfile);
}

// Print a formatted row from a matrix.
static void pr(int n, double mat[n][n], int row, FILE *outfile)
{
  Sbuf b = {0};
  sbuf_appends(&b, "          <td>");
  for (int32_t j = 0; j < n; j++) {
    double num = mat[row][j];
    if (fpclassify(num) == FP_ZERO || (-1e-7 <= num && num <= 1e-7 )) {
      sbuf_appends(&b, "0");
    } else if (isnan(num)) {
      sbuf_appends(&b, "NaN");
    } else if (isinf(num)) {
      uint8_t inf[4] = {0xE2, 0x88, 0x9E, 0};
      sbuf_appends(&b, (void*)inf);
    } else {
      sbuf_printf(&b, "%-10.4g", num);
    }
    if (j < (n - 1)) {
      sbuf_appends(&b, "</td><td>");
    }
  }
  sbuf_appends(&b, "</td>");
  sbuf_fputs(&b, outfile);
}

void matrices(Laminate *pl, FILE *outfile)
{
  char *fstr[6] = {
    "<td>N<sub>x</sub></td>",
    "<td>N<sub>y</sub></td>",
    "<td>N<sub>xy</sub></td>",
    "<td>M<sub>x</sub></td>",
    "<td>M<sub>y</sub></td>",
    "<td>M<sub>xy</sub></td>"
  };
  char *dstr[6] = {
    "<td>&epsilon;<sub>x</sub></td>",
    "<td>&epsilon;<sub>y</sub></td>",
    "<td>&gamma;<sub>xy</sub></td>",
    "<td>&kappa;<sub>x</sub></td>",
    "<td>&kappa;<sub>y</sub></td>",
    "<td>&kappa;<sub>xy</sub></td>",
  };
  fputs("<tr>\n", outfile);
  fputs("<!-- second row, stiffness or ABD matrix -->\n", outfile);
  fputs("<td colspan=\"2\">\n", outfile);
  fputs("<table border=\"1\" frame=\"vsides\" rules=\"groups\" cellpadding=\"5%\">\n", outfile);
  fputs("<caption><strong>In-plane stiffness (ABD) matrix</strong></caption>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"6\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<tbody align=\"center\">\n", outfile);
  fputs("<tr>\n", outfile);
  fputs(fstr[0], outfile);
  fputs("<td rowspan=\"6\">=</td>\n", outfile);
  pr(6, pl->ABD, 0, outfile);
  fputs("<td rowspan=\"6\">&times;</td>\n", outfile);
  fputs(dstr[0], outfile);
  fputs("</tr>\n", outfile);
  for (int32_t r = 1; r < 6; r++) {
    fputs("<tr>\n", outfile);
    fputs(fstr[r], outfile);
    pr(6, pl->ABD, r, outfile);
    fputs(dstr[r], outfile);
    fputs("</tr>\n", outfile);
  }
  fputs("</tbody>\n", outfile);
  fputs("</table>\n", outfile);
  fputs("</td>\n", outfile);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fputs("<!-- third row, transverse stiffness or H matrix -->\n", outfile);
  fputs("<td colspan=\"2\">\n", outfile);
  fputs("<table border=\"1\" frame=\"vsides\" rules=\"groups\" cellpadding=\"5%\">\n", outfile);
  fputs("<caption><strong>Transverse stiffness (H) matrix</strong></caption>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"2\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<tbody align=\"center\">\n", outfile);
  fputs("<tr>\n", outfile);
  fputs("<td>V<sub>y</sub></td>\n", outfile);
  fputs("<td rowspan=\"2\">=</td>\n", outfile);
  pr(2, pl->H, 0, outfile);
  fputs("<td rowspan=\"2\">&times;</td>\n", outfile);
  fputs("<td>&gamma;<sub>yz</sub></td>\n", outfile);
  fputs("</tr>\n", outfile);
  fputs("<tr>\n", outfile);
  fputs("<td>V<sub>x</sub></td>\n", outfile);
  pr(2, pl->H, 1, outfile);
  fputs("<td>&gamma;<sub>xz</sub></td>\n", outfile);
  fputs("</tr>\n", outfile);
  fputs("</tbody>\n", outfile);
  fputs("</table>\n", outfile);
  fputs("</td>\n", outfile);
  fputs("</tr>\n", outfile);
  char *fstr2[6] = {
    "<td>&sigma;<sub>11</sub></td>",
    "<td>&sigma;<sub>22</sub></td>",
    "<td>&sigma;<sub>33</sub></td>",
    "<td>&sigma;<sub>23</sub></td>",
    "<td>&sigma;<sub>13</sub></td>",
    "<td>&sigma;<sub>12</sub></td>",
  };
  char *dstr2[6] = {
    "<td>&epsilon;<sub>11</sub></td>",
    "<td>&epsilon;<sub>22</sub></td>",
    "<td>&epsilon;<sub>33</sub></td>",
    "<td>2&epsilon;<sub>23</sub></td>",
    "<td>2&epsilon;<sub>13</sub></td>",
    "<td>2&epsilon;<sub>12</sub></td>",
  };
  fputs("<tr>\n", outfile);
  fputs("<!-- next row, stiffness tensor -->\n", outfile);
  fputs("<td colspan=\"2\">\n", outfile);
  fputs("<table border=\"1\" frame=\"vsides\" rules=\"groups\" cellpadding=\"5%\">\n", outfile);
  fputs("<caption><strong>3D stiffness (C) tensor, contracted notation</strong></caption>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"6\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<colgroup span=\"1\"></colgroup>\n", outfile);
  fputs("<tbody align=\"center\">\n", outfile);
  fputs("<tr>\n", outfile);
  fputs(fstr2[0], outfile);
  fputs("<td rowspan=\"6\">=</td>\n", outfile);
  pr(6, pl-> C, 0, outfile),
  fputs("<td rowspan=\"6\">&times;</td>\n", outfile);
  fputs(dstr2[0], outfile);
  fputs("</tr>\n", outfile);
  for (int32_t r = 1; r < 6; r++) {
    fputs("<tr>\n", outfile);
    fputs(fstr2[r], outfile);
    pr(6, pl->C, r, outfile);
    fputs(dstr2[r], outfile);
    fputs("</tr>\n", outfile);
  }
  fputs("</tbody>\n", outfile);
  fputs("</table>\n", outfile);
  fputs("</td>\n", outfile);
  fputs("</tr>\n", outfile);
}
