// file: latex.c
// vim:fileencoding=utf-8:ft=c:tabstop=2
// LaTeX output for lamprop.
//
// Copyright © 2025 R.F. Smith <rsmith@xs4all.nl>
// SPDX-License-Identifier: MIT
// Created: 2025-08-11 20:20:22 +0200
// Last modified: 2026-05-25T02:26:02+0200

#include "core.h"
#include "stringview.h"
#include "sbuf.h"
#include "utils.h"
#include "version.h"
#include "setup.h"

#include <assert.h>
#include <stddef.h>
#include <string.h>
#include <math.h>

static void engprop(Laminate *pl, FILE *outfile);
static void matrices(Laminate *pl, FILE *outfile);
extern void text_fea(Laminate *pl, FILE *outfile);
static void ltxclean(Sv8 str, char replace, char *outbuf, ptrdiff_t outlen);

void latex_out(Laminate *pl, Options opts)
{
  char texlname[256];
  char texcname[256];
  ltxclean(pl->name, '-', texlname, 255);
  ltxclean(pl->name, ' ', texcname, 255);
  assert(pl != 0);
  fputs("\\begin{table}[!htbp]\n", opts.outfile);
  fprintf(opts.outfile, "  \\caption{\\label{tab:%s}properties of %s}\n", texlname, texcname);
  fputs("  \\centering\\footnotesize{\\rule{0pt}{10pt}\n", opts.outfile);
  fputs("  \\tiny generated by "LONG_VERSION"\\\\[3pt]}\n", opts.outfile);
  fputs("    \\begin{tabular}[t]{rcrrl}\n", opts.outfile);
  fputs("      \\multicolumn{5}{c}{\\small\\textbf{Laminate stacking}}\\\\[0.1em]\n", opts.outfile);
  fputs("      \\toprule %% \\usepackage{booktabs}\n", opts.outfile);
  fputs("      Layer & Weight & Angle & vf & Fiber type\\\\\n", opts.outfile);
  fputs("            & [g/m$^2$] & [$\\circ$] & [\\%]\\\\\n", opts.outfile);
  fputs("      \\midrule\n", opts.outfile);
  for (int32_t k = 0; k < pl->nlayers; k++) {
    Lamina *la = pl->layers + k;
    char fname[256] = {0};
    ltxclean(la->f.name, ' ', fname, 255);
    if (la->comment.data && la->comment.len) {
      fprintf(opts.outfile, "      \\multicolumn{5}{l}{%s}\\\\\n", sv8cstring(la->comment));
    } else if (la->symm) {
      fputs("      \\multicolumn{5}{l}{\\rule[0.5ex]{10mm}{1pt}symmetry line\\rule[0.5ex]{10mm}{1pt}}\\\\\n", opts.outfile);
    }
    fprintf(opts.outfile, "      %3d & %6g & %5g & %4.3g & ", k + 1, la->fiber_weight,
           180 * la->angle / M_PI, 100 * la->vf);
    fprintf(opts.outfile, "%s\\\\\n", fname);
  }
  fputs("      \\bottomrule\n", opts.outfile);
  fputs("    \\end{tabular}\\hspace{0.02\\textwidth}\n", opts.outfile);
  fputs("    \\begin{tabular}[t]{rrlrrl}\n", opts.outfile);
  fputs("      \\multicolumn{6}{c}{\\small\\textbf{Physical properties}}\\\\[0.1em]\n", opts.outfile);
  fputs("      \\toprule\n", opts.outfile);
  fputs("      Property & Value & Dimension\\\\\n", opts.outfile);
  fputs("      \\midrule\n", opts.outfile);
  fprintf(opts.outfile, "      $\\mathrm{v_f}$ & %4.1f &\\%%\\\\\n", 100 * pl->vf);
  fprintf(opts.outfile, "      $\\mathrm{w_f}$ & %4.1f &\\%%\\\\\n", 100 * pl->wf);
  fprintf(opts.outfile, "      thickness & %.2f & mm\\\\\n", pl->thickness);
  fprintf(opts.outfile, "      density & %4.2f & g/cm$^3$\\\\\n", pl->ρ);
  fprintf(opts.outfile, "      weight & %.0f & g/m$^2$\\\\\n", pl->fiber_weight + pl->resin_weight);
  fprintf(opts.outfile, "      resin & %.0f & g/m$^2$\\\\\n", pl->resin_weight);
  if (opts.eng) {
    engprop(pl, opts.outfile);
  }
  fputs("      \\bottomrule\n", opts.outfile);
  fputs("    \\end{tabular}\n", opts.outfile);
  if (opts.matrix) {
    matrices(pl, opts.outfile);
  }
  if (opts.fea) {
    fputs("  \\vbox{\n", opts.outfile);
    fputs("  \\begin{verbatim}\n", opts.outfile);
    text_fea(pl, opts.outfile);
    fputs("  \\end{verbatim}\n", opts.outfile);
    fputs("  }\n", opts.outfile);
  }
  fputs("\\end{table}\n", opts.outfile);
  fputs("\n", opts.outfile);
  fflush(opts.outfile);
}

void engprop(Laminate *pl, FILE *outfile)
{
  fputs("      \\midrule\n", outfile);
  fputs("      \\multicolumn{6}{c}{\\small\\textbf{Engineering properties}}\\\\[0.1em]\n", outfile);
  fputs("      \\multicolumn{3}{c}{\\small\\textbf{In-plane}} & \n", outfile);
  fputs("      \\multicolumn{3}{c}{\\small\\textbf{3D stiffness tensor}}\\\\[0.1em]\n", outfile);
  fprintf(outfile, "      $\\mathrm{E_x}$ & %.0f & MPa & $\\mathrm{E_x}$ & %.0f & MPa\\\\\n",
         pl->Ex, pl->tEx);
  fprintf(outfile, "      $\\mathrm{E_y}$ & %.0f & MPa & $\\mathrm{E_y}$ & %.0f & MPa\\\\\n",
         pl->Ey, pl->tEy);
  fprintf(outfile, "      $\\mathrm{E_z}$ & %.0f & MPa & $\\mathrm{E_z}$ & %.0f & MPa\\\\\n",
         pl->Ez, pl->tEz);
  fprintf(outfile, "      $\\mathrm{G_{xy}}$ & %.0f & MPa & ", pl->Gxy);
  fprintf(outfile, "$\\mathrm{G_{xy}}$ & %.0f & MPa\\\\\n", pl->tGxy);
  fprintf(outfile, "      $\\mathrm{G_{xz}}$ & %.0f & MPa & ", pl->Gxz);
  fprintf(outfile, "$\\mathrm{G_{xz}}$ & %.0f & MPa\\\\\n", pl->tGxz);
  fprintf(outfile, "      $\\mathrm{G_{yz}}$ & %.0f & MPa & ", pl->Gyz);
  fprintf(outfile, "$\\mathrm{G_{yz}}$ & %.0f & MPa\\\\\n", pl->tGyz);
  fprintf(outfile, "      $\\mathrm{\\nu_{xy}}$ & %7.5f &- & ", pl->νxy);
  fprintf(outfile, "$\\mathrm{\\nu_{xy}}$ & %7.5f &-\\\\\n", pl->tνxy);
  fprintf(outfile, "      $\\mathrm{\\nu_{yx}}$ & %7.5f &- & ", pl->νyx);
  fprintf(outfile, "$\\mathrm{\\nu_{xz}}$ & %.4f &-\\\\\n", pl->tνxz);
  fprintf(outfile, "      $\\mathrm{\\alpha_x}$ & %9.4g & K$^{-1}$ & ", pl->αx);
  fprintf(outfile, "$\\mathrm{\\nu_{yz}}$ & %7.5f &-\\\\\n", pl->tνyz);
  fprintf(outfile, "      $\\mathrm{\\alpha_y}$ & %9.4g & K$^{-1}$\\\\\n", pl->αy);
}

// Print a formatted matrix.
static void pm(int32_t n, double m[n][n], FILE *outfile)
{
  for (int32_t r = 0; r < n; r++) {
    Sbuf linebuf = {0};
    for (int32_t k = 0; k < n; k++) {
      double num = m[r][k];
      if (num > -1e-7 && num < 1e-7) {
        sbuf_appends(&linebuf, "0 & ");
      } else if (isnan(num)) {
        sbuf_appends(&linebuf, "\\mathrm{NaN} & ");
      } else if (isinf(num)) {
        sbuf_appends(&linebuf, "\\infty & ");
      } else {
        int exp = 0;
        double mantissa = frexp10(m[r][k], &exp);
        sbuf_printf(&linebuf, "%.3f", mantissa);
        sbuf_printf(&linebuf, "\\times 10^{%d} & ", exp);
      }
    } // end of columns
    linebuf.used -= 3;
    sbuf_append(&linebuf, "\\\\\n", 3);
    sbuf_fputs(&linebuf, outfile);
  }
}

void matrices(Laminate *pl, FILE *outfile)
{
  fputs("  \\vbox{\n", outfile);
  fputs("    \\vbox{\\small\\textbf{In-plane stiffness (ABD) matrix}\\\\[-3mm]\n", outfile);
  fputs("      \\tiny\\[\\left\\{\\begin{array}{c}\n", outfile);
  fputs("          N_x\\\\ N_y\\\\ N_{xy}\\\\ M_x\\\\ M_y\\\\ M_{xy}\n", outfile);
  fputs("        \\end{array}\\right\\} = \n", outfile);
  fputs("      \\left|\\begin{array}{cccccc}\n", outfile);
  //}
  pm(6, pl->ABD, outfile);
  fputs("          \\end{array}\\right| \\times\n", outfile);
  fputs("        \\left\\{\\begin{array}{c}\n", outfile);
  fputs("            \\epsilon_x\\\\[2pt] \\epsilon_y\\\\[2pt] \\gamma_{xy}\\\\[2pt]\n", outfile);
  fputs("            \\kappa_x\\\\[2pt] \\kappa_y\\\\[2pt] \\kappa_{xy}\n", outfile);
  fputs("          \\end{array}\\right\\}\\]\n", outfile);
  fputs("    }\n", outfile);
  fputs("    \\vbox{\\small\\textbf{Transverse stiffness (H) matrix}\\\\[-2mm]\n", outfile);
  fputs("      \\tiny\\[\\left\\{\\begin{array}{c}\n", outfile);
  fputs("          V_y\\\\ V_x\n", outfile);
  fputs("        \\end{array}\\right\\} = \n", outfile);
  fputs("      \\left|\\begin{array}{cc}\n", outfile);
  pm(2, pl->H, outfile);
  fputs("          \\end{array}\\right| \\times\n", outfile);
  fputs("        \\left\\{\\begin{array}{c}\n", outfile);
  fputs("            \\gamma_{yz}\\\\[2pt] \\gamma_{xz}\n", outfile);
  fputs("          \\end{array}\\right\\}\\]\n", outfile);
  fputs("    }\n", outfile);
  fputs("    \\vbox{\\small\\textbf{3D stiffness tensor (C), contracted "
       "notation}\\\\[-3mm]\n", outfile);
  fputs("      \\tiny\\[\\left\\{\\begin{array}{c}\n", outfile);
  fputs("          \\sigma_{11}\\\\ \\sigma_{22}\\\\ \\sigma_{33}\\\\"
       " \\sigma_{23}\\\\ \\sigma_{13}\\\\ \\sigma_{12}\n", outfile);
  fputs("        \\end{array}\\right\\} = \n", outfile);
  fputs("      \\left|\\begin{array}{cccccc}\n", outfile);
  pm(6, pl->C, outfile);
  fputs("          \\end{array}\\right| \\times\n", outfile);
  fputs("        \\left\\{\\begin{array}{c}\n", outfile);
  fputs("            \\epsilon_{11}\\\\[2pt] \\epsilon_{22}\\\\[2pt]"
       " \\epsilon_{33}\\\\[2pt]\n", outfile);
  fputs("            2\\cdot\\epsilon_{23}\\\\[2pt] 2\\cdot\\epsilon_{13}\\\\"
       "[2pt] 2\\cdot\\epsilon_{12}\n", outfile);
  fputs("          \\end{array}\\right\\}\\]\n", outfile);
  fputs("    }\n", outfile);
  fputs("  }\n", outfile);
}

void ltxclean(Sv8 str, char replace, char *outbuf, ptrdiff_t outlen)
{
  assert(replace != 0);
  assert(outbuf);
  assert(outlen > 0);
  ptrdiff_t len = str.len < outlen ? str.len : outlen;
  memset(outbuf, 0, outlen);
  for (int j = 0; j < len; j++) {
    switch (str.data[j]) {
      case '#':
      case '_':
      case '&':
      case '%':
      case '~':
      case '^':
      case '{':
      case '}':
      case '[':
      case ']':
      case '\\':
        // Replace character.
        outbuf[j] = replace;
        break;
      default:
        outbuf[j] = str.data[j];
        break;
    }
  }
  if (outbuf[--len] == replace) {
    outbuf[len] = 0;
  }
}
