// file: latex.c
// vim:fileencoding=utf-8:ft=c:tabstop=2
//
// Author: R.F. Smith <rsmith@xs4all.nl>
// Copyright © 2025 R.F. Smith <rsmith@xs4all.nl>
// Created: 2025-08-11 20:20:22 +0200
// Last modified: 2025-08-16T23:26:31+0200

#include "core.h"
#include "version.h"

#include <string.h>
#include <stdio.h>
#include <math.h>

static void engprop(Laminate *pl);
static void matrices(Laminate *pl);
extern void text_fea(Laminate *pl);

void latex_out(Laminate *pl, bool eng, bool mat, bool fea)
{
  // Escape underscores in the name.
  char texlname[pl->name.len*2];
  memset(texlname, 0, pl->name.len*2);
  for (int32_t j = 0, k = 0; j < pl->name.len; j++, k++) {
    if (pl->name.data[j] == '_') {
      texlname[k++] = '\\';
    }
    texlname[k] = pl->name.data[j];
  }
  puts("\\begin{table}[!htbp]");
  printf("  \\caption{\\label{tab:%s}properties of %s}\n", texlname, texlname);
  puts("  \\centering\\footnotesize{\\rule{0pt}{10pt}");
  puts("  \\tiny generated by lamprop-c version "VERSION"\n");
  puts("    \\begin{tabular}[t]{rcrrl}");
  puts("      \\multicolumn{5}{c}{\\small\\textbf{Laminate stacking}}\\\\[0.1em]");
  puts("      \\toprule %% \\usepackage{booktabs}");
  puts("      Layer & Weight & Angle & vf & Fiber type\\\\");
  puts("            & [g/m$^2$] & [$\\circ$] & [\\%]\\\\");
  puts("      \\midrule");
  for (int32_t k = 0; k < pl->nlayers; k++) {
    Lamina *la = pl->layers + k;
    printf("      %3d & %6g & %5g & %4.3g & ", k+1, la->fiber_weight,
           180*la->angle/M_PI, 100*la->vf);
    printf("%s\\\\\n", sv8cstring(la->f.name));
  }
  puts("      \\bottomrule");
  puts("    \\end{tabular}\\hspace{0.02\\textwidth}");
  puts("    \\begin{tabular}[t]{rrlrrl}");
  puts("      \\multicolumn{6}{c}{\\small\\textbf{Physical properties}}\\\\[0.1em]");
  puts("      \\toprule");
  puts("      Property & Value & Dimension\\\\");
  puts("      \\midrule");
  printf("      $\\mathrm{v_f}$ & %4.1f &\\%%\\\\\n", 100*pl->vf);
  printf("      $\\mathrm{w_f}$ & %4.1f &\\%%\\\\\n", 100*pl->wf);
  printf("      thickness & %.2f & mm\\\\\n", pl->thickness);
  printf("      density & %4.2f & g/cm$^3$\\\\\n", pl->ρ);
  printf("      weight & %.0f & g/m$^2$\\\\\n", pl->fiber_weight + pl->resin_weight);
  printf("      resin & %.0f & g/m$^2$\\\\\n", pl->resin_weight);
  if (eng) {
    engprop(pl);
  }
  puts("      \\bottomrule");
  puts("    \\end{tabular}");
  if (mat) {
    matrices(pl);
  }
  if (fea) {
    puts("  \\vbox{");
    puts("  \\begin{verbatim}");
    text_fea(pl);
    puts("  \\end{verbatim}");
    puts("  }");
  }
  puts("\\end{table}");
  puts("");
  fflush(stdout);
}

void engprop(Laminate *pl)
{
  puts("      \\midrule");
  puts("      \\multicolumn{6}{c}{\\small\\textbf{Engineering properties}}\\\\[0.1em]");
  puts("      \\multicolumn{3}{c}{\\small\\textbf{In-plane}} & ");
  puts("      \\multicolumn{3}{c}{\\small\\textbf{3D stiffness tensor}}\\\\[0.1em]");
  printf("      $\\mathrm{{E_x}}$ & %8.0f & MPa & $\\mathrm{{E_x}}$ & %8.0f & MPa\\\\\n",
         pl->Ex, pl->tEx);
  printf("      $\\mathrm{{E_y}}$ & %8.0f & MPa & $\\mathrm{{E_y}}$ & %8.0f & MPa\\\\\n",
         pl->Ey, pl->tEy);
  printf("      $\\mathrm{{E_z}}$ & %8.0f & MPa & $\\mathrm{{E_z}}$ & %8.0f & MPa\\\\\n",
         pl->Ez, pl->tEz);
  printf("      $\\mathrm{{G_{{xy}}}}$ & %8.0f & MPa &\n", pl->Gxy);
  printf("      $\\mathrm{{G_{{xy}}}}$ & %8.0f & MPa\\\\\n", pl->tGxy);
  printf("      $\\mathrm{{G_{{xz}}}}$ & %8.0f & MPa &\n", pl->Gxz);
  printf("      $\\mathrm{{G_{{xz}}}}$ & %8.0f & MPa\\\\\n", pl->tGxz);
  printf("      $\\mathrm{{G_{{yz}}}}$ & %8.0f & MPa &\n", pl->Gyz);
  printf("      $\\mathrm{{G_{{yz}}}}$ & %8.0f & MPa\\\\\n", pl->tGyz);
  printf("      $\\mathrm{{\\nu_{{xy}}}}$ & %.4f &- &\n", pl->νxy);
  printf("      $\\mathrm{{\\nu_{{xy}}}}$ & %.4f &-\\\\\n", pl->tνxy);
  printf("      $\\mathrm{{\\nu_{{yx}}}}$ & %.4f &- &\n", pl->νyx);
  printf("      $\\mathrm{{\\nu_{{xz}}}}$ & %.4f &-\\\\\n", pl->tνxz);
  printf("      $\\mathrm{{\\alpha_x}}$ & %.4g & K$^{{-1}}$ &\n", pl->αx);
  printf("      $\\mathrm{{\\nu_{{yz}}}}$ & %.4f &-\\\\\n", pl->tνyz);
  printf("      $\\mathrm{{\\alpha_y}}$ & %.4g & K$^{{-1}}$\\\\\n", pl->αy);
}

void matrices(Laminate *pl)
{
  puts("  \\vbox{");
  puts("    \\vbox{\\small\\textbf{In-plane stiffness (ABD) matrix}\\\\[-3mm]");
  puts("      \\tiny\\[\\left\\{\\begin{array}{c}");
  puts("          N_x\\\\ N_y\\\\ N_{xy}\\\\ M_x\\\\ M_y\\\\ M_{xy}");
  puts("        \\end{array}\\right\\} = ");
  puts("      \\left|\\begin{array}{cccccc}");
  for (int32_t r = 0; r < 6; r++) {
    printf("%10e & %10e & %10e & %10e & %10e & %10e\\\\\n",
           pl->ABD[r][0], pl->ABD[r][1], pl->ABD[r][2],
           pl->ABD[r][3], pl->ABD[r][4], pl->ABD[r][5]);
  }
  puts("          \\end{array}\\right| \\times");
  puts("        \\left\\{\\begin{array}{c}");
  puts("            \\epsilon_x\\\\[2pt] \\epsilon_y\\\\[2pt] \\gamma_{xy}\\\\[2pt]");
  puts("            \\kappa_x\\\\[2pt] \\kappa_y\\\\[2pt] \\kappa_{xy}");
  puts("          \\end{array}\\right\\}\\]");
  puts("    }");
  puts("    \\vbox{\\small\\textbf{Transverse stiffness (H) matrix}\\\\[-2mm]");
  puts("      \\tiny\\[\\left\\{\\begin{array}{c}");
  puts("          V_y\\\\ V_x");
  puts("        \\end{array}\\right\\} = ");
  puts("      \\left|\\begin{array}{cc}");
  printf("%10e & %10e\\\\\n", pl->H[0][0], pl->H[0][1]);
  printf("%10e & %10e\\\\\n", pl->H[1][0], pl->H[1][1]);
  puts("          \\end{array}\\right| \\times");
  puts("        \\left\\{\\begin{array}{c}");
  puts("            \\gamma_{yz}\\\\[2pt] \\gamma_{xz}");
  puts("          \\end{array}\\right\\}\\]");
  puts("    }");
  puts("    \\vbox{\\small\\textbf{3D stiffness tensor (C), contracted "
       "notation}\\\\[-3mm]");
  puts("      \\tiny\\[\\left\\{\\begin{array}{c}");
  puts("          \\sigma_{11}\\\\ \\sigma_{22}\\\\ \\sigma_{33}\\\\"
       " \\sigma_{23}\\\\ \\sigma_{13}\\\\ \\sigma_{12}");
  puts("        \\end{array}\\right\\} = ");
  puts("      \\left|\\begin{array}{cccccc}");
  for (int32_t r = 0; r < 6; r++) {
    printf("%10e & %10e & %10e & %10e & %10e & %10e\\\\\n",
           pl->C[r][0], pl->C[r][1], pl->C[r][2],
           pl->C[r][3], pl->C[r][4], pl->C[r][5]);
  }
  puts("          \\end{array}\\right| \\times");
  puts("        \\left\\{\\begin{array}{c}");
  puts("            \\epsilon_{11}\\\\[2pt] \\epsilon_{22}\\\\[2pt]"
       " \\epsilon_{33}\\\\[2pt]");
  puts("            2\\cdot\\epsilon_{23}\\\\[2pt] 2\\cdot\\epsilon_{13}\\\\"
       "[2pt] 2\\cdot\\epsilon_{12}");
  puts("          \\end{array}\\right\\}\\]");
  puts("    }");
  puts("  }");
}
