// file: latex.c
// vim:fileencoding=utf-8:ft=c:tabstop=2
//
// Author: R.F. Smith <rsmith@xs4all.nl>
// Copyright © 2025 R.F. Smith <rsmith@xs4all.nl>
// Created: 2025-08-11 20:20:22 +0200
// Last modified: 2026-02-01T01:55:03+0100

#include "core.h"
#include "stringview.h"
#include "sbuf.h"
#include "version.h"

#include <string.h>
#include <stdio.h>
#include <math.h>

static void engprop(Laminate *pl);
static void matrices(Laminate *pl);
extern void text_fea(Laminate *pl);

void latex_out(Laminate *pl, bool eng, bool mat, bool fea)
{
  // Escape underscores in the name.
  char texlname[pl->name.len*2];
  memset(texlname, 0, pl->name.len*2);
  for (int32_t j = 0, k = 0; j < pl->name.len; j++, k++) {
    if (pl->name.data[j] == '_') {
      texlname[k++] = '\\';
    }
    texlname[k] = pl->name.data[j];
  }
  puts("\\begin{table}[!htbp]");
  printf("  \\caption{\\label{tab:%s}properties of %s}\n", texlname, sv8cstring(pl->name));
  puts("  \\centering\\footnotesize{\\rule{0pt}{10pt}");
  puts("  \\tiny generated by lamprop-c version "VERSION"\\\\[3pt]}");
  puts("    \\begin{tabular}[t]{rcrrl}");
  puts("      \\multicolumn{5}{c}{\\small\\textbf{Laminate stacking}}\\\\[0.1em]");
  puts("      \\toprule %% \\usepackage{booktabs}");
  puts("      Layer & Weight & Angle & vf & Fiber type\\\\");
  puts("            & [g/m$^2$] & [$\\circ$] & [\\%]\\\\");
  puts("      \\midrule");
  for (int32_t k = 0; k < pl->nlayers; k++) {
    Lamina *la = pl->layers + k;
    printf("      %3d & %6g & %5g & %4.3g & ", k+1, la->fiber_weight,
           180*la->angle/M_PI, 100*la->vf);
    printf("%s\\\\\n", sv8cstring(la->f.name));
  }
  puts("      \\bottomrule");
  puts("    \\end{tabular}\\hspace{0.02\\textwidth}");
  puts("    \\begin{tabular}[t]{rrlrrl}");
  puts("      \\multicolumn{6}{c}{\\small\\textbf{Physical properties}}\\\\[0.1em]");
  puts("      \\toprule");
  puts("      Property & Value & Dimension\\\\");
  puts("      \\midrule");
  printf("      $\\mathrm{v_f}$ & %4.1f &\\%%\\\\\n", 100*pl->vf);
  printf("      $\\mathrm{w_f}$ & %4.1f &\\%%\\\\\n", 100*pl->wf);
  printf("      thickness & %.2f & mm\\\\\n", pl->thickness);
  printf("      density & %4.2f & g/cm$^3$\\\\\n", pl->ρ);
  printf("      weight & %.0f & g/m$^2$\\\\\n", pl->fiber_weight + pl->resin_weight);
  printf("      resin & %.0f & g/m$^2$\\\\\n", pl->resin_weight);
  if (eng) {
    engprop(pl);
  }
  puts("      \\bottomrule");
  puts("    \\end{tabular}");
  if (mat) {
    matrices(pl);
  }
  if (fea) {
    puts("  \\vbox{");
    puts("  \\begin{verbatim}");
    text_fea(pl);
    puts("  \\end{verbatim}");
    puts("  }");
  }
  puts("\\end{table}");
  puts("");
  fflush(stdout);
}

void engprop(Laminate *pl)
{
  puts("      \\midrule");
  puts("      \\multicolumn{6}{c}{\\small\\textbf{Engineering properties}}\\\\[0.1em]");
  puts("      \\multicolumn{3}{c}{\\small\\textbf{In-plane}} & ");
  puts("      \\multicolumn{3}{c}{\\small\\textbf{3D stiffness tensor}}\\\\[0.1em]");
  printf("      $\\mathrm{E_x}$ & %.0f & MPa & $\\mathrm{E_x}$ & %.0f & MPa\\\\\n",
         pl->Ex, pl->tEx);
  printf("      $\\mathrm{E_y}$ & %.0f & MPa & $\\mathrm{E_y}$ & %.0f & MPa\\\\\n",
         pl->Ey, pl->tEy);
  printf("      $\\mathrm{E_z}$ & %.0f & MPa & $\\mathrm{E_z}$ & %.0f & MPa\\\\\n",
         pl->Ez, pl->tEz);
  printf("      $\\mathrm{G_{xy}}$ & %.0f & MPa & ", pl->Gxy);
  printf("$\\mathrm{G_{xy}}$ & %.0f & MPa\\\\\n", pl->tGxy);
  printf("      $\\mathrm{G_{xz}}$ & %.0f & MPa & ", pl->Gxz);
  printf("$\\mathrm{G_{xz}}$ & %.0f & MPa\\\\\n", pl->tGxz);
  printf("      $\\mathrm{G_{yz}}$ & %.0f & MPa & ", pl->Gyz);
  printf("$\\mathrm{G_{yz}}$ & %.0f & MPa\\\\\n", pl->tGyz);
  printf("      $\\mathrm{\\nu_{xy}}$ & %7.5f &- & ", pl->νxy);
  printf("$\\mathrm{\\nu_{xy}}$ & %7.5f &-\\\\\n", pl->tνxy);
  printf("      $\\mathrm{\\nu_{yx}}$ & %7.5f &- & ", pl->νyx);
  printf("$\\mathrm{\\nu_{xz}}$ & %.4f &-\\\\\n", pl->tνxz);
  printf("      $\\mathrm{\\alpha_x}$ & %9.4g & K$^{-1}$ & ", pl->αx);
  printf("$\\mathrm{\\nu_{yz}}$ & %7.5f &-\\\\\n", pl->tνyz);
  printf("      $\\mathrm{\\alpha_y}$ & %9.4g & K$^{-1}$\\\\\n", pl->αy);
}


static void pm(int32_t n, double m[n][n])
{
  for (int32_t r = 0; r < n; r++) {
    Sbuf linebuf = {0};
    Sv8 zero = SV8("0.000000e+00");
    for (int32_t k = 0; k < n; k++) {
      char numbuf[30] = {0};
      snprintf(numbuf, 30, "%10e", m[r][k]);
      Sv8 content = {numbuf, strlen(numbuf)};
      if (sv8equals(content, zero)) {
        sbuf_append(&linebuf, "0 & ", 4);
        continue;
      }
      Sv8Cut cut = sv8cut(content, 'e');
      if (cut.ok == false) { // no e found, should not happen.
        continue;
      }
      // Add mantissa to buffer.
      sbuf_append(&linebuf, cut.head.data, cut.head.len);
      bool neg = false, advance = true;
      if (cut.tail.data[0] == '-') {
        neg = true;
      } else if (cut.tail.data[0] != '+') {
        advance = false;
      }
      while (advance == true && cut.tail.len > 0) {
        cut.tail.data++;
        cut.tail.len--;
        if (cut.tail.data[0] != '0') {
          advance = false;
        }
      }
      if (neg) {
        cut.tail.data--;
        cut.tail.data[0] = '-';
        cut.tail.len++;
      }
      sbuf_append(&linebuf, "\\times 10^{", 11);
      sbuf_append(&linebuf, cut.tail.data, cut.tail.len);
      sbuf_append(&linebuf, "} & ", 4);
    } // end of columns
    linebuf.used -= 3;
    sbuf_append(&linebuf, "\\\\\n", 3);
    sbuf_fputs(&linebuf, stdout);
  }
}

void matrices(Laminate *pl)
{
  puts("  \\vbox{");
  puts("    \\vbox{\\small\\textbf{In-plane stiffness (ABD) matrix}\\\\[-3mm]");
  puts("      \\tiny\\[\\left\\{\\begin{array}{c}");
  puts("          N_x\\\\ N_y\\\\ N_{xy}\\\\ M_x\\\\ M_y\\\\ M_{xy}");
  puts("        \\end{array}\\right\\} = ");
  puts("      \\left|\\begin{array}{cccccc}");
  //}
  pm(6, pl->ABD);
  puts("          \\end{array}\\right| \\times");
  puts("        \\left\\{\\begin{array}{c}");
  puts("            \\epsilon_x\\\\[2pt] \\epsilon_y\\\\[2pt] \\gamma_{xy}\\\\[2pt]");
  puts("            \\kappa_x\\\\[2pt] \\kappa_y\\\\[2pt] \\kappa_{xy}");
  puts("          \\end{array}\\right\\}\\]");
  puts("    }");
  puts("    \\vbox{\\small\\textbf{Transverse stiffness (H) matrix}\\\\[-2mm]");
  puts("      \\tiny\\[\\left\\{\\begin{array}{c}");
  puts("          V_y\\\\ V_x");
  puts("        \\end{array}\\right\\} = ");
  puts("      \\left|\\begin{array}{cc}");
  pm(2, pl->H);
  puts("          \\end{array}\\right| \\times");
  puts("        \\left\\{\\begin{array}{c}");
  puts("            \\gamma_{yz}\\\\[2pt] \\gamma_{xz}");
  puts("          \\end{array}\\right\\}\\]");
  puts("    }");
  puts("    \\vbox{\\small\\textbf{3D stiffness tensor (C), contracted "
       "notation}\\\\[-3mm]");
  puts("      \\tiny\\[\\left\\{\\begin{array}{c}");
  puts("          \\sigma_{11}\\\\ \\sigma_{22}\\\\ \\sigma_{33}\\\\"
       " \\sigma_{23}\\\\ \\sigma_{13}\\\\ \\sigma_{12}");
  puts("        \\end{array}\\right\\} = ");
  puts("      \\left|\\begin{array}{cccccc}");
  pm(6, pl->C);
  puts("          \\end{array}\\right| \\times");
  puts("        \\left\\{\\begin{array}{c}");
  puts("            \\epsilon_{11}\\\\[2pt] \\epsilon_{22}\\\\[2pt]"
       " \\epsilon_{33}\\\\[2pt]");
  puts("            2\\cdot\\epsilon_{23}\\\\[2pt] 2\\cdot\\epsilon_{13}\\\\"
       "[2pt] 2\\cdot\\epsilon_{12}");
  puts("          \\end{array}\\right\\}\\]");
  puts("    }");
  puts("  }");
}
