// matrix5.h
// Functions for manipulating 5 × 5 matrices.
//
// Generated by the matgen.pl script version 1.1 on 2025-08-12.
// This generated code is not copyrighted since it is the result of a
// purely mechanical transformation, and free for anyone to use.
//
// The matgen.pl script is © 2009 R.F. Smith <rsmith@xs4all.nl>

#pragma once

#include <stdbool.h>

#define LIMIT 1e-10

#ifdef __cplusplus
extern "C" {
#endif

// Makes a matrix into the unity matrix
extern void mat_unity5(double a[5][5]);

// Copies matrix a into b
extern void mat_cpy5(double a[5][5], double b[5][5]);

// Multiplies a matrix with a vector
extern void mat_xform5(double m[5][5], double v[5], double mv[5]);

// Multiplies two matrices
extern void mat_mul5(double a[5][5], double b[5][5],
                     double ab[5][5]);

// Converts a matrix to Row Echelon Form.
extern void mat_ref5(double m[5][5], double ref[5][5]);

// Calculate the determinant of the matrix.
// Uses mat_ref internally.
extern double mat_det5(double m[5][5]);

// Inverts a matrix if possible.
extern bool mat_inv5(double m[5][5], double i[5][5]);

// Print the matrix on stdout
extern void mat_print5(char *name, double m[5][5]);

// Transpose the matrix a.
extern void mat_xpose5(double a[5][5]);

// Cleans matrix a of small numbers, sets them to 0.
extern void mat_clean5(double a[5][5]);

#ifdef __cplusplus
}
#endif

/* EOF matrix5.h */
