// matrix2.c
// Functions for manipulating 2 × 2 matrices.
//
// Generated by the matgen.pl script version 1.1 on 2025-08-10.
// This generated code is not copyrighted since it is the result of a
// purely mechanical transformation, and free for anyone to use.
//
// The matgen.pl script is © 2009 R.F. Smith <rsmith@xs4all.nl>

#include "matrix2.h"

#include <assert.h>
#include <stdio.h>
#include <string.h>

void mat_unity2(double a[2][2])
{
  assert(a!=NULL);
  //  Row 0
  a[0][0] = 1.0;
  a[0][1] = 0.0;
  //  Row 1
  a[1][0] = 0.0;
  a[1][1] = 1.0;
}

void mat_cpy2(double a[2][2], double b[2][2])
{
  assert(a!=NULL);
  assert(b!=NULL);
  // Row 0
  b[0][0] = a[0][0];
  b[0][1] = a[0][1];
  // Row 1
  b[1][0] = a[1][0];
  b[1][1] = a[1][1];
}

void mat_xform2(double m[2][2], double v[2], double mv[2])
{
  double res[2];
  assert(m!=NULL);
  assert(v!=NULL);
  assert(mv!=NULL);
  res[0]  = m[0][0]*v[0];
  res[0] += m[0][1]*v[1];
  res[1]  = m[1][0]*v[0];
  res[1] += m[1][1]*v[1];
  memcpy(mv, res, 2*sizeof(double));
}

void mat_mul2(double a[2][2], double b[2][2], double ab[2][2])
{
  double res[2][2];
  assert(a!=NULL);
  assert(b!=NULL);
  assert(ab!=NULL);
  res[0][0]  = a[0][0]*b[0][0];
  res[0][0] += a[0][1]*b[1][0];
  if (res[0][0] < LIMIT && res[0][0] > -LIMIT) {
    res[0][0] = 0.0;
  }
  res[0][1]  = a[0][0]*b[0][1];
  res[0][1] += a[0][1]*b[1][1];
  if (res[0][1] < LIMIT && res[0][1] > -LIMIT) {
    res[0][1] = 0.0;
  }
  res[1][0]  = a[1][0]*b[0][0];
  res[1][0] += a[1][1]*b[1][0];
  if (res[1][0] < LIMIT && res[1][0] > -LIMIT) {
    res[1][0] = 0.0;
  }
  res[1][1]  = a[1][0]*b[0][1];
  res[1][1] += a[1][1]*b[1][1];
  if (res[1][1] < LIMIT && res[1][1] > -LIMIT) {
    res[1][1] = 0.0;
  }
  memcpy(ab, res, 2*2*sizeof(double));
}

bool mat_inv2(double m[2][2], double i[2][2])
{
  double m2[2][2], inv[2][2], f, diag;
  assert(m!=NULL);
  assert(i!=NULL);
  mat_cpy2(m, m2);
  mat_unity2(inv);
  // If the diagonal is zero, matrix is not invertable
  diag = m2[0][0];
  diag *= m2[1][1];
  if (diag > -LIMIT && diag < LIMIT) {
    return false;
  }
  // Empty the lower half of the matrix
  // Row 1
  f = m2[1][0]/m2[0][0];
  m2[1][0] -= f*m2[0][0];
  inv[1][0] -= f*inv[0][0];
  m2[1][1] -= f*m2[0][1];
  inv[1][1] -= f*inv[0][1];
  /* Now empty the upper half */
  // Column 1
  f = m2[0][1]/m2[1][1];
  inv[0][0] -= f*inv[1][0];
  m2[0][0] -= f*m2[1][0];
  inv[0][1] -= f*inv[1][1];
  m2[0][1] -= f*m2[1][1];
  // Correct the magnitude of the rows
  inv[0][0] /= m2[0][0];
  inv[0][1] /= m2[0][0];
  inv[1][0] /= m2[1][1];
  inv[1][1] /= m2[1][1];
  mat_cpy2(inv, i);
  return true;
}

void mat_print2(char *name, double m[2][2])
{
  printf("matrix %s =\n", name);
  printf("|%g %g|\n", m[0][0], m[0][1]);
  printf("|%g %g|\n", m[1][0], m[1][1]);
}
void mat_xpose2(double a[2][2])
{
  assert(a!=0);
  double res[2][2];
  // Row 0
  res[0][0] = a[0][0];
  res[0][1] = a[1][0];
  // Row 1
  res[1][0] = a[0][1];
  res[1][1] = a[1][1];
  memcpy(a, res, 2*2*sizeof(double));
}

void mat_clean2(double a[2][2])
{
  if (a[0][0] < LIMIT && a[0][0] > -LIMIT) {
    a[0][0] = 0.0;
  }
  if (a[0][1] < LIMIT && a[0][1] > -LIMIT) {
    a[0][1] = 0.0;
  }
  if (a[1][0] < LIMIT && a[1][0] > -LIMIT) {
    a[1][0] = 0.0;
  }
  if (a[1][1] < LIMIT && a[1][1] > -LIMIT) {
    a[1][1] = 0.0;
  }
}

// EOF matrix2.c
