// matrix6.h
// Functions for manipulating 6 × 6 matrices.
//
// Generated by the matgen.pl script version 1.1 on 2025-08-10.
// This generated code is not copyrighted since it is the result of a
// purely mechanical transformation, and free for anyone to use.
//
// The matgen.pl script is © 2009 R.F. Smith <rsmith@xs4all.nl>

#pragma once

#include <stdbool.h>

#define LIMIT 1e-10

#ifdef __cplusplus
extern "C" {
#endif

// Makes a matrix into the unity matrix
extern void mat_unity6(double a[6][6]);

// Copies matrix a into b
extern void mat_cpy6(double a[6][6], double b[6][6]);

// Multiplies a matrix with a vector
extern void mat_xform6(double m[6][6], double v[6], double mv[6]);

// Multiplies two matrices
extern void mat_mul6(double a[6][6], double b[6][6],
                     double ab[6][6]);

// Inverts a matrix, if possible.
extern bool mat_inv6(double m[6][6], double i[6][6]);

// Print the matrix on stdout
extern void mat_print6(char *name, double m[6][6]);

// Transpose a matrix
extern void mat_xpose6(double a[6][6]);

// Cleans matrix a of small numbers, sets them to 0.
extern void mat_clean6(double a[6][6]);

#ifdef __cplusplus
}
#endif

/* EOF matrix6.h */
