// matrix2.h
// Functions for manipulating 2 × 2 matrices.
//
// Generated by the matgen.pl script version 1.1 on 2025-08-10.
// This generated code is not copyrighted since it is the result of a
// purely mechanical transformation, and free for anyone to use.
//
// The matgen.pl script is © 2009 R.F. Smith <rsmith@xs4all.nl>

#pragma once

#include <stdbool.h>

#define LIMIT 1e-10

#ifdef __cplusplus
extern "C" {
#endif

// Makes a matrix into the unity matrix
extern void mat_unity2(double a[2][2]);

// Copies matrix a into b
extern void mat_cpy2(double a[2][2], double b[2][2]);

// Multiplies a matrix with a vector
extern void mat_xform2(double m[2][2], double v[2], double mv[2]);

// Multiplies two matrices
extern void mat_mul2(double a[2][2], double b[2][2],
                     double ab[2][2]);

// Inverts a matrix, if possible.
extern bool mat_inv2(double m[2][2], double i[2][2]);

// Print the matrix on stdout
extern void mat_print2(char *name, double m[2][2]);

// Transpose a matrix
extern void mat_xpose2(double a[2][2]);

// Cleans matrix a of small numbers, sets them to 0.
extern void mat_clean2(double a[2][2]);

#ifdef __cplusplus
}
#endif

/* EOF matrix2.h */
