// file: text.c
// vim:fileencoding=utf-8:ft=c:tabstop=2
//
// Copyright © 2025 R.F. Smith <rsmith@xs4all.nl>
// SPDX-License-Identifier: MIT
// Created: 2025-08-09 22:26:21 +0200
// Last modified: 2025-08-09T22:56:37+0200

#include "core.h"
#include "version.h"

#include <stdio.h>
#include <math.h>

void text_out(Laminate *pl, bool eng, bool mat, bool fea)
{
  printf("\nGenerated by lamprop version %s\n", VERSION);
  printf("laminate: %s\n", sv8cstring(pl->name));
  printf("thickness: %.2f mm, density: %4.2f g/cm³\n",
         pl->thickness, pl->ρ);
  printf("fiber volume fraction: %4.1f%%, ", 100*pl->vf);
  printf("fiber weight fraction: %4.1f%%\n", 100*pl->wf);
  printf("laminate weight: %.0f g/m², ", pl->fiber_weight + pl->resin_weight);
  printf("resin consumption: %.0f g/m²\n", pl->resin_weight);
  printf("num weight angle   vf fiber\n");
  printf("    [g/m²]   [°]  [%%]\n");
  for (int32_t k = 0; k < pl->nlayers; k++) {
    Lamina *la = pl->layers + k;
    printf("%3d %6g %5g %4.3g ", k+1, la->fiber_weight, 180*la->angle/M_PI, 100*la->vf);
    printf("%s\n", sv8cstring(la->f.name));
  }
}
