// file: text.c
// vim:fileencoding=utf-8:ft=c:tabstop=2
//
// Copyright © 2025 R.F. Smith <rsmith@xs4all.nl>
// SPDX-License-Identifier: MIT
// Created: 2025-08-09 22:26:21 +0200
// Last modified: 2025-08-10T16:09:02+0200

#include "core.h"
#include "version.h"

#include <stdio.h>
#include <math.h>

static void engprop(Laminate *pl);
static void matrices(Laminate *pl);
static void _fea(Laminate *pl);

void text_out(Laminate *pl, bool eng, bool mat, bool fea)
{
  printf("\nGenerated by lamprop version %s\n", VERSION);
  printf("laminate: %s\n", sv8cstring(pl->name));
  printf("thickness: %.2f mm, density: %4.2f g/cm³\n",
         pl->thickness, pl->ρ);
  printf("fiber volume fraction: %4.1f%%, ", 100*pl->vf);
  printf("fiber weight fraction: %4.1f%%\n", 100*pl->wf);
  printf("laminate weight: %.0f g/m², ", pl->fiber_weight + pl->resin_weight);
  printf("resin consumption: %.0f g/m²\n", pl->resin_weight);
  printf("num weight angle   vf fiber\n");
  printf("    [g/m²]   [°]  [%%]\n");
  for (int32_t k = 0; k < pl->nlayers; k++) {
    Lamina *la = pl->layers + k;
    printf("%3d %6g %5g %4.3g ", k+1, la->fiber_weight, 180*la->angle/M_PI, 100*la->vf);
    printf("%s\n", sv8cstring(la->f.name));
  }
  if (eng) {
    engprop(pl);
  }
  if (mat) {
    matrices(pl);
  }
  if (fea) {
    _fea(pl);
  }
}

void engprop(Laminate *pl)
{
  puts("In-plane engineering properties:");
  printf("E_x  = %.0f MPa, E_y  = %.0f MPa, E_z  = %.0f MPa\n",
         pl->Ex, pl->Ey, pl->Ez);
  printf("G_xy  = %.0f MPa, G_xz  = %.0f MPa, G_yz  = %.0f MPa\n",
         pl->Gxy, pl->Gxz, pl->Gyz);
  printf("ν_xy = %7.5f\n", pl->νxy);
  printf("α_x =  %9.4g K⁻¹, α_y =  %9.4g K⁻¹\n", pl->αx, pl->αy);
  puts("Engineering properties derived from 3D stiffness matrix:");
  printf("E_x  = %.0f MPa, E_y  = %.0f MPa, E_z  = %.0f MPa\n",
         pl->tEx, pl->tEy, pl->tEz);
  printf("G_xy  = %.0f MPa, G_xz  = %.0f MPa, G_yz  = %.0f MPa\n",
         pl->tGxy, pl->tGxz, pl->tGyz);
  printf("ν_xy = %.3f, ν_xz = %.3f, ν_yz = %.3f\n",  pl->tνxy, pl->tνxz, pl->tνyz);
}

void matrices(Laminate *pl)
{
}

void _fea(Laminate *pl)
{
}
